Create mlhajipur.json
ml-comm/ddns pull request #13
Opened 2024-11-11 04:57 UTC by Anushka-codergirl

## Related Issue

## Types of changes

- [ ] New Subdomain Request
- [ ] Modification to Existing Subdomain
- [ ] Github Repository Update
- [ ] Other

## Description

## Checklist:

- [ ] This change will not affect the existing subdomains.
- [ ] I have checked the existing subdomains and ensured that my new subdomain nor modification is not a duplicate.

2024-11-11 06:27 UTC, BRAVO68WEB commented
Hey @Anushka-codergirl , thank you for making a pull request to our project.

There are few issues, in your request. 

1. Create a Issue [here](https://github.com/ml-comm/ddns/issues/new?assignees=&labels=request&projects=&template=REQUEST.yml&title=%5BREQUEST%5D%3A+) about your request.
2. We are unable to understand what domain you want to link with?

2024-11-11 06:27 UTC, BRAVO68WEB commented
Please start by creating a Issue at [https://github.com/ml-comm/ddns/issues/new?assignees=&labels=request&projects=&template=REQUEST.yml&title=%5BREQUEST%5D%3A+](here)

2024-11-11 06:28 UTC, BRAVO68WEB requested changes
Approval Issue not found; Invalid Config

2024-11-11 06:28 UTC, BRAVO68WEB commented
@smanitech

2024-11-11 07:41 UTC, Anushka-codergirl commented
Done👍

2024-11-11 08:03 UTC, Ba3a-G requested changes
Hey @Anushka-codergirl,
We are unable to understand your request. 
Here's what you need to write in each of the parameters:

- owner
  - username: _your GitHub username_
  - email: _your Organisation's email_
- target
  - CNAME
    - name: _your desired subdomain_
    - value: _your existing hosted website_

Also, you need to change the filename from _mlhajipur_ to _hajipur_.
Please RTFM [here](https://ddns.mlcommunity.dev/format.html).

2024-11-11 13:46 UTC, Anushka-codergirl commented
I got it!

2024-11-11 15:05 UTC, Ba3a-G requested changes

2024-11-11 15:05 UTC, Ba3a-G commented on domains/hajipur.json
> +            "value": "Anushka-codergirl.github.io"
Hey, the website at Anushka-codergirl.github.io seems to be a personal portfolio. We can provide subdomains only to community websites.

2024-11-12 02:51 UTC, BRAVO68WEB commented
@Anushka-codergirl, can you let us know, where is your website repo on github?

2024-11-12 07:05 UTC, Anushka-codergirl commented
https://github.com/Anushka-codergirl/MLHajipur - I will push the code once it's ready!

2024-11-12 08:02 UTC, BRAVO68WEB commented
Got it, we are closing this PR for now. Recreate the pr once the website is built. We will assist you that time.

2024-11-12 08:02 UTC, closed without merging